### ISSUE TITLE
Перетворити вимогу в скаргу: `Resolving variable '${claim.access.token}' failed: AttributeError: access`

### ISSUE THREAD

**Issue by AvchinnikovaOksana** [openprocurement/robot_tests#161]
_OpenUA - "Можливість подати скаргу на умови більше ніж за 4 дні до завершення періоду подання пропозицій"_

В kw `Перетворити вимогу в скаргу` ожидается, что будет получен параметр `${claim.access.token}`, но драйвер нашей площадки такими данными не обладает. Не могу ее вернуть из `Створити вимогу`.

`Resolving variable '${claim.access.token}' failed: AttributeError: access`

**Comment by mykhaly** [comment]
Цей рядок
`${tender}=  set_access_key  ${tender}  ${claim.access.token}`
 буде замінено на
`${tender}=  set_access_key  ${tender}  ${USERS.users['${username}'].access_token}`

**Comment by mykhaly** [comment]
Вирішується в https://github.com/openprocurement/robot_tests/pull/131/

**Comment by selurvedu** [comment]
Done.
