### ISSUE TITLE
Resolving variable '${TENDER['LOT_ID']}' failed: KeyError: 'LOT_ID'

### ISSUE THREAD

**Issue by AvchinnikovaOksana** [openprocurement/robot_tests#173]
meatTender - provider - "Можливість дочекатися початку аукціону" 

Воспроизводится ли у Вас следующая ошибка или я что-то неверно стянула? 
```
Можливість дочекатися початку аукціону                                | FAIL |
Resolving variable '${TENDER['LOT_ID']}' failed: KeyError: 'LOT_ID'
```

[Log.html](https://www.dropbox.com/s/lkb0j7wpowtpud3/meatTender.html?dl=0)

**Comment by Leits** [comment]
Вирішено у гілці master.
