### ISSUE TITLE
"Відображення заголовку другого лоту" - некорректно опеределяется путь к искомому элементу

### ISSUE THREAD

**Issue by AvchinnikovaOksana** [openprocurement/robot_tests#177]
**MultiLotTender - viewer**
Для теста `Відображення заголовку другого лоту` определяется путь к элементу 	`${field} = lots[0].title`, 
как и для теста `Відображення заголовку першого лоту`
`${field} = lots[0].title`

[log.html] (https://www.dropbox.com/s/ssulz7eww5chtiv/log.html?dl=0)

**Comment by Leits** [comment]
Вирішено у гілці master.
