### ISSUE TITLE
No keyword with name 'Звірити координати тендера' found

### ISSUE THREAD

**Issue by AvchinnikovaOksana** [openprocurement/robot_tests#180]
MultiItemTender - viewer - Відображення координат доставки позицій закупівлі багатопредметного тендера
```
Відображення координат доставки позицій закупівлі багатопредметного тендера

	No keyword with name 'Звірити координати тендера' found. Did you mean:
    keywords.Звірити Координати Доставки Тендера
```
[log.html](https://www.dropbox.com/s/xo6faytrrtj4t69/log.html?dl=0)

**Comment by mykhaly** [comment]
`Звірити координати доставки предметів закупівлі багатопредметного тендера`
https://github.com/openprocurement/robot_tests/blob/master/op_robot_tests/tests_files/multiItemTender.robot#L59

**Comment by AvchinnikovaOksana** [comment]
Не поняла я намека :blush:
вот эта вещь, вроде, действительно нигде не встречается в keywords
https://github.com/openprocurement/robot_tests/blob/master/op_robot_tests/tests_files/keywords.robot#L460

**Comment by mykhaly** [comment]
Мабуть, це випадково пропустили. Як я бачу, замість `Звірити координати тендера` мало би бути `Звірити координати доставки тендера`. Буде виправлено, дякую за знаходження помилки :)

**Comment by AvchinnikovaOksana** [comment]
Спасибо, ждем)

**Comment by Leits** [comment]
Вирішено у гілці master.
