### ISSUE TITLE
items[0].description в "Відображення опису нової шостої позиції закупівлі багатопредметного тендера"

### ISSUE THREAD

**Issue by AvchinnikovaOksana** [openprocurement/robot_tests#181]
**MultiItemTender - viewer**
```
Відображення опису нової шостої позиції закупівлі багатопредметного тендера
Відображення опису нової сьомої позиції закупівлі багатопредметного тендера
```
При получении данных из тендера передается некорректный номер item-а
`items[0].description`

[log.html](https://www.dropbox.com/sh/t1sjbg6hof6pvwn/AABpMXvaJRapHWDBpLPo8djda?dl=0)

**Comment by selurvedu** [comment]
Ref: #134.

**Comment by Leits** [comment]
Вирішено у гілці master.
