### ISSUE TITLE
'${tender.data.auctionUrl}' failed: AttributeError: auctionUrl

### ISSUE THREAD

**Issue by AvchinnikovaOksana** [openprocurement/robot_tests#182]
**SingleItemTender - provider - Можливість вичитати посилання на аукціон для глядача**
`FAIL	Resolving variable '${tender.data.auctionUrl}' failed: AttributeError: auctionUrl`

[log.html](https://www.dropbox.com/s/86ac9enr908l2mj/log.html?dl=0)

**Comment by selurvedu** [comment]
Чи часто це виникає? Коли воно з’явилось вперше?

JFYI: URL з’явився, але не відразу: https://lb.api-sandbox.openprocurement.org/api/2.3/tenders/035587b16dfb4196b622fabca0a24cc2?opt_pretty=1

**Comment by AvchinnikovaOksana** [comment]
Первый раз 14.04, с тех пор повторилось 5 раз
[log.html](https://www.dropbox.com/s/86ac9enr908l2mj/log.html?dl=0)

но тут есть и другие ошибки, сейчас они не повторяются, наверно с долгим изменением статусов связанные
```
Неможливість завантажити документ другим учасником після закінчення прийому пропозицій
FAIL	Користувач Tender_User1 зміг виконати "Завантажити документ в ставку"
```
А для viewer до этого теста дело не доходило - поскольку тесты шустрые и не дожидались перехода тендера в нужный статус.

**Comment by selurvedu** [comment]
Вияснив причину: за дві хвилини (`Sleep 120`) вже встигає змінитись статус тендера, але ще не встигає заплануватись аукціон (саме для цього там і було `Sleep 120`).
