### ISSUE TITLE
MultiLotTender - Подати цінову пропозицію - AttributeError: Attribute not found: lots

### ISSUE THREAD

**Issue by AvchinnikovaOksana** [openprocurement/robot_tests#183]
**MultiLotTender - provider - Можливість подати цінову пропозицію першим учасником**
```
Можливість подати цінову пропозицію першим учасником
FAIL	AttributeError: Attribute not found: lots
```

[log.html](https://www.dropbox.com/s/dxx6825et7gwjzz/log.html?dl=0)

**Comment by Leits** [comment]
Вирішено у гілці master.
