### ISSUE TITLE
Отредактировать файл initial_data.py

### ISSUE THREAD

**Issue by Rzaporozhets** [openprocurement/robot_tests#26]
1. Сделать файл однотипным, что бы было удобно всем площадкам.
Данные примеры касаются словаря "test_tender_data", с остальными нужно сделать тоже самое.
"test_tender_data_multiple_lots", "test_question_data", "test_complaint_data", "test_bid_data", "auction_bid"

Исправить ошибки:
Только файл  "test_tender_data" 
-  "description": u"папір і картон гофровані, паперова й картонна тара" - Сделать первую букву заглавной

Все файлы включая "test_tender_data" 
 - "region": u"м. Київ" - заменить на u"Київська область"
 - "description": u"Cartons" - Заменить на u"Картонки"

Добавить значение в еще 2 языках, где значении без приставке  - Украинский язык
Сейчас - "currency": u"UAH"
Нужно сделать  - "currency": u"грн.", "currency_ru": u"грн.", "currency_en": u"UAH"
Применяем еще к таким полям:
"address":
       "countryName": u"Україна",
        "region": u"Київська область",
        "locality": u"м. Київ",
"deliveryAddress": 
       "countryName": u"Україна",
        "region": u"Київська область",
        "locality": u"м. Київ",

"description": u"Cartons"
"name": u"кілограм"

**Comment by selurvedu** [comment]
Спасибі за репорт. Як ви могли помітити, я час від часу здійснюю
переоформлення файлів з кодом, яке не впливає на їх функціонування, а
потрібне лише для краси. Файл initial_data.py теж був на черзі, і змін
до нього потрібно було трохи більше. Ви саме вчасно :). Пізніше я
відповім детальніше щодо всіх пунктів.

Забігаючи трохи наперед, скажу ще дещо про вхідні дані. Значення деяких
полів мають бути не-hard-coded. Це має виглядати так: для кожного з цих
полів є набір можливих значень, з якого кожен раз рандомно або за певним
правилом вибирається одне і з ним створюється тендер. Це потрібно для
того, щоб перевірити, чи здатні майданчики правильно прийняти, обробити
і видати усі значення із тих наборів даних, які вони зобов'язані
підтримувати, в різноманітних комбінаціях. Далі можна перевіряти, як
майданчик реагує не лише на правильні, а й на помилкові вхідні дані (чи
приймає він їх, чи не приймає, чи приймає, але інтерпретує неправильно і
так далі).

Наразі ми маємо одні й ті самі картонки, один і той самий Київ, одні й
ті самі кілограми – будемо це змінювати. @myroslav, прошу мене
поправити, якщо я неточно висловився.

**Comment by Rzaporozhets** [comment]
Хорошо, тогда ждем изменений =)
По поводу "Далі можна перевіряти, як майданчик реагує не лише на правильні,
а й на помилкові вхідні дані" , Нам бы сначала настроить работу с
правильными данными, а потом можем расширять тесты =)
Сейчас мой тест очень зависит от файла initial_data.py , вы бы не могли
приблизительно сказать сроки его рефакторинга, что бы я планировал время,
был бы вам очень признателен.

2015-12-01 0:51 GMT+02:00 selurvedu <notifications@github.com>:

> Спасибі за репорт. Як ви могли помітити, я час від часу здійснюю
> переоформлення файлів з кодом, яке не впливає на їх функціонування, а
> потрібне лише для краси. Файл initial_data.py теж був на черзі, і змін
> до нього потрібно було трохи більше. Ви саме вчасно :). Пізніше я
> відповім детальніше щодо всіх пунктів.
>
> Забігаючи трохи наперед, скажу ще дещо про вхідні дані. Значення деяких
> полів мають бути не-hard-coded. Це має виглядати так: для кожного з цих
> полів є набір можливих значень, з якого кожен раз рандомно або за певним
> правилом вибирається одне і з ним створюється тендер. Це потрібно для
> того, щоб перевірити, чи здатні майданчики правильно прийняти, обробити
> і видати усі значення із тих наборів даних, які вони зобов'язані
> підтримувати, в різноманітних комбінаціях. Далі можна перевіряти, як
> майданчик реагує не лише на правильні, а й на помилкові вхідні дані (чи
> приймає він їх, чи не приймає, чи приймає, але інтерпретує неправильно і
> так далі).
>
> Наразі ми маємо одні й ті самі картонки, один і той самий Київ, одні й
> ті самі кілограми – будемо це змінювати. @myroslav, прошу мене
> поправити, якщо я неточно висловився.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openprocurement/robot_tests/issues/26#issuecomment-160787087>
> .
>



-- 
_________________________________________________________

Best regards,

Zaporozhets Roman

QA Automation Engineer

Prom.ua, Tiu.ru, Deal.by, Satu.kz

address: Kharkivske Highway, 201/203, office 316, 02000, Kiev, Ukraine

phone: +38 (067) 99-416-00

skype: zaporogech

**Comment by Rzaporozhets** [comment]
И еще, когда будите менять файл добавьте для Prom.ua 
Сейчас:
"minimalStep": {
        "amount": 100, 
}
Хочу что бы добавили:
"minimalStep": {
        "amount": 100,
        "Prom_amount": 2500,   - Почему 2500 - это 5% от сумы бюджета, нас это поле вводиться автоматически. Т.к. Бюджет "hard-coded" на 50000
}

**Comment by selurvedu** [comment]
2500 підставляється javascript'ом автоматично при вписуванні суми 50000?

**Comment by Rzaporozhets** [comment]
Да, автоматически,  javascript'ом  5% от суммы веденную в бюджет.

2015-12-01 23:39 GMT+02:00 selurvedu <notifications@github.com>:

> 2500 підставляється javascript'ом автоматично при вписуванні суми 50000?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openprocurement/robot_tests/issues/26#issuecomment-161103987>
> .
>



-- 
_________________________________________________________

Best regards,

Zaporozhets Roman

QA Automation Engineer

Prom.ua, Tiu.ru, Deal.by, Satu.kz

address: Kharkivske Highway, 201/203, office 316, 02000, Kiev, Ukraine

phone: +38 (067) 99-416-00

skype: zaporogech

**Comment by Rzaporozhets** [comment]
Повторю вопрос, по поводу приблизительных сроков рефакторинга.

**Comment by selurvedu** [comment]
@Rzaporozhets, більшу частину пропонованих вами змін ми мусимо узгодити... Опишу детальніше.

Варіації полів з суфіксами `_en` і `_ru` допустимі не для всіх string'ових полів. Їх список можна глянути [тут](http://api-docs.openprocurement.org/en/latest/search.html?q=multilingual&check_keywords=yes&area=default). Якщо біля поля написано "multilingual", то варіанти на інших мовах допустимі. Якщо ні, то БД/API їх не прийме. Інформація в документації не вичерпна, найактуальнішим і найбільш докладним є [цей файл](https://github.com/openprocurement/openprocurement.api/blob/master/src/openprocurement/api/models.py) (пошукайте в ньому `_en` і `_ru`). Щоб якесь із полів зробити "multilingual", недостатньо буде змінити код `robot_tests` – потрібно міняти код `openprocurement.api`.

Тепер трохи конкретніше про окремі поля.

1. Адреси.
  * Наразі варіанти з `_en` і `_ru` допустимі лише для назви країни, але не для `locality` або `region`. Джерело – [тут](https://github.com/openprocurement/openprocurement.api/blob/master/src/openprocurement/api/models.py#L215).
  * `countryName_ru` і `countryName_en` я додам.
  * `region` не буду міняти з `u"м. Київ"` на `u"Київська область"` через те, що міста Київ і Севастополь мають спеціальний статус і розглядаються як окремий регіон (див. коментар в [Gitter](https://gitter.im/openprocurement/robot_tests?at=5658941ce34e2efc2fbfafda)).
  * Про решту полів, які стосуються адреси, @myroslav сказав в тому ж повідомленні на Gitter.
2. `value.currency`, `minimalStep.currency` залишиться в одному екземплярі. Як підказує [код](https://github.com/openprocurement/openprocurement.api/blob/master/src/openprocurement/api/models.py#L171) з `openprocurement.api`, в цьому полі міститься код валюти із трьох латинських букв, який відповідає стандарту ISO 4217. Врешті решт, всі майданчики зчитують його з ЦБД в однаковому вигляді, а відображають вже як їм заманеться.
3. `item.unit.name`: додам `_ru` і `_en`.
4. `items.classification.description` – там дійсно помилка і мусить бути "Картонки". Я додам `description_en` і `description_ru` з цих [json/yaml](http://opendata.org.ua/dataset/cpv).
5. `items.additionalClassifications.description` з малої літери – виправлю. Додам, що case sensitive даних у нас не так вже й багато, і більшість схожих проблем не виникає, якщо переводити рядки в lowercase перед порівнянням.
6. Про `prom_amount`. Наскільки я розумію з ваших [слів](https://gitter.im/openprocurement/robot_tests?at=5656e2d0e34e2efc2fbf7be1а) в Gitter, `minimalStep.amount` при виконанні тесту не збігається з `minimalStep.amount` в initial_data, бо JS вписує 2500, а в initial_data – 100. Чи можливо змінити те, що вписав JS? Якщо так, то чи є причини для того, щоб не зробити це – проігнорувати автоматично обчислене 2500 і замість нього вписати 100?

З цього issue все. Якщо я пропустив щось звідси або з Gitter – дайте знати.

Щодо термінів – ті зміни, які я назвав можливими, можна дооформити сьогодні, але від них буде мало користі з тим, що ми ще не вирішили решту питань.

З повагою.

**Comment by Rzaporozhets** [comment]
Про prom_amount.  - могу обойти, так и сделаю.
По поводу "Варіації полів з суфіксами _en і _ru ", я изначально писал что сделать не для всех полей, а для статических. Буду ждать изменений.

**Comment by selurvedu** [comment]
@Rzaporozhets, всі зміни готові. https://github.com/openprocurement/robot_tests/pull/27#issuecomment-161792729
Чи буде їх достатньо?

**Comment by Rzaporozhets** [comment]
Раз мы решили оставить одни файл test_tender_data и test_tender_data_multiple_lots для всех площадок - удалите "prom_test_tender_data".
По поводу областей, я все равно не доволен, если уже вводить области, то делать все одного типа. А делать исключения для Севастополя и Киева...
Все остальное  - устраивает.
Еще один вопрос по примечаниям "# Error @prom when "Тестовый тендер" и т.д. в файле initial_data - Зачем они ?

**Comment by selurvedu** [comment]
> Раз мы решили оставить одни файл test_tender_data и test_tender_data_multiple_lots для всех площадок - удалите "prom_test_tender_data".

Чудово, я саме хотів підняти це питання.

> `Error @prom when "Тестовый тендер"`

Мабуть, колись воно валилось і title вписали латинський, щоб працювало з Промом: https://github.com/openprocurement/robot_tests/commit/8441602fc0edc19d297a63aa1d9efc326dce8823 . Схоже, зараз вони неактуальні і їх можна стерти.

**Comment by selurvedu** [comment]
>  По поводу областей, я все равно не доволен, если уже вводить области, то делать все одного типа. А делать исключения для Севастополя и Киева...

Справа в тім, що регіон – не те саме, що область, хоч зазвичай ці поняття ми розуміємо як синоніми. Ось список регіонів України на сайті ВР [0] (їх 27). Цей список складений згідно з ст. 133 Конституції України [1].

В випадках Севастополя і Києва ви можете не показувати в себе на сайті, що регіон – це місто, але при роботі з ЦБД в поле region мусить приходити саме місто. В даних initial_data містяться дані в формі, яку приймає ЦБД, а виглядати на сайті вони можуть по-іншому, але тоді порівнювати їх на відповідність стає складніше і потрібні всякі mapping'и та if'и.

[0]: http://w1.c1.rada.gov.ua/pls/z7502/a002
[1]: http://zakon4.rada.gov.ua/laws/show/254к/96-вр/paran4829#n4829

**Comment by selurvedu** [comment]
@Rzaporozhets, чи є ще невирішені питання в цьому issue?

**Comment by Rzaporozhets** [comment]
​Добрый день!

Да, его можно закрыть. В любом случае, если что-то захотим добавить после
рефакторинга, то лучше это сделать в новой задаче. ​

2016-01-26 5:21 GMT+02:00 selurvedu <notifications@github.com>:

> @Rzaporozhets <https://github.com/Rzaporozhets>, чи є ще невирішені
> питання в цьому issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openprocurement/robot_tests/issues/26#issuecomment-174798258>
> .
>



-- 
_________________________________________________________

Best regards,

Zaporozhets Roman

QA Automation Engineer

Prom.ua, Tiu.ru, Deal.by, Satu.kz

address: Kharkivske Highway, 201/203, office 316, 02000, Kiev, Ukraine

phone: +38 (067) 99-416-00

skype: zaporogech

**Comment by selurvedu** [comment]
Окей.
