### ISSUE TITLE
Добавить переменную времени в initial_data.py

### ISSUE THREAD

**Issue by Rzaporozhets** [openprocurement/robot_tests#29]
Во всех словарях, где есть даты:
        "enquiryPeriod": {
            "startDate": (now).isoformat(),
            "endDate": (now + timedelta(minutes=1)).isoformat()
        },
        "tenderPeriod": {
            "startDate": (now + timedelta(minutes=2)).isoformat(),
            "endDate": (now + timedelta(minutes=(2 + period_interval))).isoformat()
        }
Нужно добавить еще одну переменную "start_period_interval", которая будет присваиваться к датам :
        "enquiryPeriod": {
            "startDate": (now).isoformat(),
            "endDate": (now + timedelta(minutes=1)).isoformat()
        },
        "tenderPeriod": {
            "startDate": (now + timedelta(minutes=2)).isoformat(),
       }

Для Prom.ua пока хватит добавления "start_period_interval"

Возможно для какой-то площадки нужно будет добавить еще одну переменную.

**Comment by selurvedu** [comment]
@Rzaporozhets Чи все добре в https://github.com/openprocurement/robot_tests/issues/30#issuecomment-174796683? Чи потрібно додавати затримки для `startDate`?

**Comment by Rzaporozhets** [comment]
Добрый день, извините что с запозданием отвечаю, немного болел.
Для прома нужен "startDate" и  я бы его добавил, вдруг еще кому нужно будет, а по умолчанию можно установить дефолтное значение. Спасибо.

**Comment by selurvedu** [comment]
Зроблено: https://github.com/openprocurement/robot_tests/commit/382838471fa2bfbc45141a6ec86bb265956f5b0c https://github.com/openprocurement/robot_tests/commit/30dba375650cf6b38fd56e62500ec6b9be793e5a
Зараз є інша проблема (для всіх майданчиків використовуються однакові затримки), але конкретно ця – вирішена.
