### ISSUE TITLE
Відредагувати файл initial_data.py та brokers.yaml. Змінити час закінчення періодів. 

### ISSUE THREAD

**Issue by yboi** [openprocurement/robot_tests#30]
У зв’язку з вчорашньою розмовою:
Пропоную Зробити в файлі brokers.yaml зміни.
Відповідно зміни в inital_data.py.
Також потрібні зміни в service_keyword.py
Закінчення періоду обговорень = 12хв
Початок періоду прийому пропозицій = 13хв
Закінчення періоду прийому пропозицій = 20хв
Саме такі хвилини необхідні для проходження тестів, в подальшому можливе зменшення/редагування цих даних.
Я це зроблю і видам коміт, який зможете переглянути і оскаржити/підтвердити.

**Comment by selurvedu** [comment]
Яких майданчиків стосується вказаний час?

**Comment by yboi** [comment]
Це стосується E-tender, Publicbid, Newtend, Netcast.
На Smarttender ще тести не розроблялись.
На UAtender реалізовано тільки owner, але тут також повинний буде бути такий час як і у більшості майданчиків.

**Comment by Rzaporozhets** [comment]
Я тут создал задачку, тоже по этому поводу.

**Comment by yboi** [comment]
Я створив задачку і роблю її, сьогодні думаю видам коміт!

**Comment by Rzaporozhets** [comment]
Так у вас же хардкод данные... давайте сделаем переменную, которая подойдем всем...

**Comment by yboi** [comment]
так я сворю і буде в коміті, для код ревю!

**Comment by selurvedu** [comment]
> Також потрібні зміни в service_keyword.py
Які?

Щодо тривалості періодів маю що сказати, опишу сьогодні протягом дня.

**Comment by yboi** [comment]
Прошу до код рев’ю!
https://github.com/yboi/robot_tests/commit/e0a181379aaec16b89719928d8207aee6fd2cfea

**Comment by Rzaporozhets** [comment]
Прому подходит.

**Comment by w-be** [comment]
@yboi Я вже подивився є пару коментів (прям в коміті).

**Comment by yboi** [comment]
@selurvedu Я запускав і тести через Quinta проходять успішно, прошу дати свою оцінку/рев’ю

**Comment by yboi** [comment]
@w-be дякую за рев’ю  
https://github.com/yboi/robot_tests/commit/e1c9130f4998028c7503763456c34a57989cfd01

**Comment by selurvedu** [comment]
@w-be @yboi @Rzaporozhets
Ваші коментарі і коміти в сумі дали щось таке: https://github.com/openprocurement/robot_tests/commit/af807b6ce23edfdc39ac183cc61d03b1a90d755f, https://github.com/openprocurement/robot_tests/commit/2dbb59c67ac9c0d247fd65e78bf57dd777418066
Гляньте, чи все там добре.

**Comment by Rzaporozhets** [comment]
На первый взгляд вроде все хорошо, будем переписывать - посмотрим.

2016-01-26 5:17 GMT+02:00 selurvedu <notifications@github.com>:

> @w-be <https://github.com/w-be> @yboi <https://github.com/yboi>
> @Rzaporozhets <https://github.com/Rzaporozhets>
> Ваші коментарі і коміти в сумі дали щось таке: af807b6
> <https://github.com/openprocurement/robot_tests/commit/af807b6ce23edfdc39ac183cc61d03b1a90d755f>,
> 2dbb59c
> <https://github.com/openprocurement/robot_tests/commit/2dbb59c67ac9c0d247fd65e78bf57dd777418066>
> Гляньте, чи все там добре.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openprocurement/robot_tests/issues/30#issuecomment-174796683>
> .
>



-- 
_________________________________________________________

Best regards,

Zaporozhets Roman

QA Automation Engineer

Prom.ua, Tiu.ru, Deal.by, Satu.kz

address: Kharkivske Highway, 201/203, office 316, 02000, Kiev, Ukraine

phone: +38 (067) 99-416-00

skype: zaporogech
