### ISSUE TITLE
Адреса доставки. Створити словник через ZIP код, населених пунктів, регіонів.

### ISSUE THREAD

**Issue by yboi** [openprocurement/robot_tests#31]
Зробити словник через ZIP код, населених пунктів, регіонів.
Питання чи робити такий словник не повним, наприклад 10 наборів значень?
Так як в Україні 31 000  ZIP кодів.
Щоб в файлі inial_data.py не були одні і ті ж дані.
"deliveryAddress": {
                    "countryName": u"Україна",
                    "countryName_ru": u"Украина",
                    "countryName_en": "Ukraine",
                    "postalCode": fake.postalcode(),
                    "region": u"м. Київ",
                    "locality": u"м. Київ",
І щоб дані були трьохмовні не тільки  countryName а й locality i region

**Comment by selurvedu** [comment]
>  І щоб дані були трьохмовні не тільки countryName а й locality i region

Чи є для цього потреба? Майданчики віддають назви міст не в тому вигляді, в якому вони вводились?
Ще гляньте мою відповідь тут: https://github.com/openprocurement/robot_tests/issues/26#issuecomment-161474220

**Comment by w-be** [comment]
@selurvedu, як нарахунок не вводити нових 3-х мовних полів, а просто розширити можливий набір даних до 10 (чи до 20-30), з умовою, щоб дані були правильні?

**Comment by selurvedu** [comment]
Через faker? Добре, це було в планах. "Можливий набір даних" – це що саме має бути?

**Comment by w-be** [comment]
'47142': {
        'region': u'Тернопільська',
        'locality': u'Потуторів'}
+ ще 9 таких наборів, в додачу до існуючого 
"region": u"м. Київ",
"locality": u"м. Київ",

**Comment by selurvedu** [comment]
Я так розумію, це те саме, що описав @yboi, а як це стосуєтсья багатомовних полів?

**Comment by yboi** [comment]
@selurvedu наприклад майданчик UAtender він на рос. мові і м.Київ вибрати не можемо, тому б добре зробити 'region' багатомовним
http://joxi.ru/5mddkVauvvDXom

**Comment by w-be** [comment]
Ніяк, це відповідь на питання ""Можливий набір даних" – це що саме має бути?"

**Comment by selurvedu** [comment]
@w-be, а, зрозуміло.
@yboi, можна зробити щось схоже на словник для CPV, і порівнювати з даними із нього. Перед порівнянням вказати, яку мову будемо порівнювати, або ж послідовно порівняти з `uk`, `ru`, `en`. Один з цих варіантів я імплементую.

**Comment by selurvedu** [comment]
Done: #138.
