### ISSUE TITLE
Використовувати скорочення в "unit"

### ISSUE THREAD

**Issue by yboi** [openprocurement/robot_tests#32]
На майданчиках E-tender і Netcast використуваються скорочення для 'unit' -> 'name'
E-tender:
![162598c676](https://cloud.githubusercontent.com/assets/13013223/11741288/a5583b26-a000-11e5-95a7-9cb55a56e8c4.jpg)
Netcast:
![9223568646](https://cloud.githubusercontent.com/assets/13013223/11741340/10192632-a001-11e5-85e2-ebb515870494.jpg)

**Comment by selurvedu** [comment]
Для DZO (ex Netcast) мінімальний список скорочень реалізовано. в Etender – ще ні.

**Comment by selurvedu** [comment]
This should belong to https://github.com/openprocurement/robot_tests.broker.etender and https://github.com/openprocurement/robot_tests.broker.newtend, hence closing.
+invalid
