### ISSUE TITLE
Newtend. Розробникам Newtend потрібно додати можливість вводити данні з клавіатури в поля дат.

### ISSUE THREAD

**Issue by yboi** [openprocurement/robot_tests#33]
Данні в поля наклікуються - вводяться мишкою, не можна вписати. Це призвело до написання досить незрозумілих й обмежених по можливих вхідних значеннях функцій.
Це покращить код для автоматизації, стане більш зрозумілим.

**Comment by selurvedu** [comment]
Цікавий факт:

В Newtend є державні торги і комерційні торги. Комерційні мають інший інтерфейс, і там можливо вводити дати з клавіатури. Можливо, вони скоро ту фічу перенесуть.

**Comment by myroslav** [comment]
CC: @SlaOne

**Comment by SlaOne** [comment]
в реализации питон + селениум использую такую штуку для ввода даты в эти хитрые поля:

self.driver.execute_script('arguments[0].removeAttribute("readonly", "readonly")', self.enquiry_start)
self.enquiry_start.send_keys(TimesPeriods.current_date.strftime("%Y-%m-%d"))

возможно это не самы правильный способ, но все таки немного проще того механизма, что описан в tests_files\brokers\newtend_service.py и не зависит от того, есть дейт пикер или мы там что-то поменяем

**Comment by myroslav** [comment]
Ідеально, якби ви дійсно поміняли ті поля, щоб вони допускали введення з
клавіатури. Ви уявляєте собі сліпого користувача, який вводить той
JavaScript в консолі, щоб ввести дату?

Тому і важливо, щоб розробник тестів мав доступ до розробників сайту, щоб
Допиляти сам сайт, і щоб як простіше тестилося, так і простіше
користувалося.

Зараз наприклад оту дату з clipboard не вставиш. І тут не треба бути
сліпим, досить мати мало часу і багато тендерів, які треба оголосити, і
будеш згадувати розробників "незлим тихим словом" :)

On Wednesday, 27 January 2016, Sviatoslav <notifications@github.com> wrote:

> в реализации питон + селениум использую такую штуку для ввода даты в эти
> хитрые поля:
>
> self.driver.execute_script('arguments[0].removeAttribute("readonly",
> "readonly")', self.enquiry_start)
>
> self.enquiry_start.send_keys(TimesPeriods.current_date.strftime("%Y-%m-%d"))
>
> возможно это не самы правильный способ, но все таки немного проще того
> механизма, что описан в tests_files\brokers\newtend_service.py и не зависит
> от того, есть дейт пикер или мы там что-то поменяем
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openprocurement/robot_tests/issues/33#issuecomment-175285225>
> .
>


-- 
....................................................................................................................................
Myroslav Opyr   ▪   CTO   ▪    Quintagroup   ▪   +1.917.475.4725   ▪
http://quintagroup.com
˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙

**Comment by selurvedu** [comment]
This should belong to https://github.com/openprocurement/robot_tests.broker.newtend, hence closing.
+invalid

**Comment by selurvedu** [comment]
This should belong to https://github.com/openprocurement/robot_tests.broker.newtend, hence closing.
+invalid
