### ISSUE TITLE
Дати для Netcast.

### ISSUE THREAD

**Issue by yboi** [openprocurement/robot_tests#34]
На Netcast дату доставки можна задати мінімально +10 днів
Кінець періоду обговорення 4 дня
Початок періоду пропозицій стартує мінімально 4 дня і може закінчитись мінімально через 9 днів
Також на Netcast немає можливості вибрати годину (немає полів), автоматично присвоює 16:00
Це ускладнює проходження тестів.

**Comment by selurvedu** [comment]
Складно проводити автоматизовані тести з такими довгими інтервалами... Без очікування чотирьох діб можна тестувати хіба що створення тендера і період уточнень. Для всього іншого потрібно, щоб майданчик встановив коротші часові інтервали на тестовому сервері.

**Comment by w-be** [comment]
Маю інформацію по обходу: "це можна обійти, активувавши в кабінеті "режим тестування порталу". Та проводити аукціони день-в-день, виставивши вручну всі дати сьогоднішніми. Але тоді на кожен період відводиться по 10 хв".

**Comment by selurvedu** [comment]
Я перевірю, як воно працює.

**Comment by selurvedu** [comment]
Перевірив, маю наступне:
```json
"enquiryPeriod": {
    "startDate": "2016-02-03T07:14:48.086998+02:00",
    "endDate": "2016-02-03T07:19:47+02:00"
},
```
```json
"tenderPeriod": {
    "startDate": "2016-02-03T07:19:47+02:00",
    "endDate": "2016-02-03T07:29:47+02:00"
},
```
Тут enquiryPeriod має 5 хвилин, tenderPeriod – 10 хвилин.

**Comment by w-be** [comment]
Має бути достатньо. Ці затримки регулює майданчик, якщо в процесі розробки тестів виявиться, що мало самі і зможуть змінити, в коді майдачика.

**Comment by selurvedu** [comment]
Поки що не вийде це вирішити і питання відкладається: https://gitter.im/openprocurement/robot_tests?at=56b256e73bb131bb121b2632

**Comment by selurvedu** [comment]
> Поки що не вийде це вирішити і питання відкладається: https://gitter.im/openprocurement/robot_tests?at=56b256e73bb131bb121b2632

Resolved in #133.
