### ISSUE TITLE
Широта і Довгота. Вставлення ° за допомогою Selenium.

### ISSUE THREAD

**Issue by yboi** [openprocurement/robot_tests#36]
"deliveryLocation": {
          "latitude": u"49.8500° N",
          "longitude": u"24.0167° E"
" ° " градус не копіюється Selenium 
Як можна обійти?

**Comment by myroslav** [comment]
В оновленій версії даних на цьому місці float, і відповідальністю тесту
буде привести ті координати до вигляду, який сприймає майданчик. Якщо буде
складно генерувати, то ми одразу в initial data запишемо ці дані в інших
форматах, подібно до того як різними мовами є деякі властивості

On Wednesday, 16 December 2015, yboi <notifications@github.com> wrote:

> "deliveryLocation": {
> "latitude": u"498500° N",
> "longitude": u"240167° E"
> " ° " градус не копіюється Selenium
> Як можна обійти?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openprocurement/robot_tests/issues/36>.
>


-- 
....................................................................................................................................
Myroslav Opyr   ▪   CTO   ▪    Quintagroup   ▪   +1.917.475.4725   ▪
http://quintagroup.com
˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙

**Comment by yboi** [comment]
@myroslav 
Було б добре використовувати дані про "deliveryLocation" в initial_data.py в функції test_tender_data
такі ж як у ф-ції test_tender_data_multiple_lots
                "deliveryLocation": {
                    "latitude": 49.8500,
                    "longitude": 24.0167

**Comment by myroslav** [comment]
Це вже зроблено, просто ще не потрапило в master...

https://github.com/openprocurement/robot_tests/commit/d5ee5a90ac962611fcf66f1d19ad26972f9d8f9f

On Wednesday, 16 December 2015, yboi <notifications@github.com> wrote:

> @myroslav <https://github.com/myroslav>
> Було б добре використовувати дані про "deliveryLocation" в initial_data.py
> в функції test_tender_data
> такі ж як у ф-ції test_tender_data_multiple_lots
> "deliveryLocation": {
> "latitude": 49.8500,
> "longitude": 24.0167
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openprocurement/robot_tests/issues/36#issuecomment-165069684>
> .
>


-- 
....................................................................................................................................
Myroslav Opyr   ▪   CTO   ▪    Quintagroup   ▪   +1.917.475.4725   ▪
http://quintagroup.com
˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙

**Comment by yboi** [comment]
@myroslav зрозумів, дякую!
