### ISSUE TITLE
Добавить расширения к используемым при загрузке файлам

### ISSUE THREAD

**Issue by AvchinnikovaOksana** [openprocurement/robot_tests#45]
Просьба указывать расширения файлов при их генерации, а так же при передаче их имен/путей к ним.

Пример: 
текущее содержимое переменной ${filepath} в тесте "Завантажити документ другим учасником"
`"c:\users\admin\appdata\local\temp\tmprcpfzd"`

ожидаемое содержимое переменной после выполнения доработки `"c:\users\admin\appdata\local\temp\tmprcpfzd.txt"`

**Comment by selurvedu** [comment]
Вирішено, дякую за репорт.
