### ISSUE TITLE
Ошибка в тесте "Можливість відповісти на запитання"

### ISSUE THREAD

**Issue by AvchinnikovaOksana** [openprocurement/robot_tests#62]
Ошибка:
```
Можливість відповісти на запитання                                                          | FAIL |
Resolving variable '${tender.data.questions[0].id}' failed: AttributeError: questions
```

_Условия запуска тестов:_
**пример**: `-s multiLotTender -v viewer:PrivatMarket_Viewer -v provider:PrivatMarket_Provider -v api_version:0.12`
**обязательное условие**: ответ на вопрос выполняется через апи (Quinta).

[log.html](https://www.dropbox.com/s/wvgo0iutvz2jex0/log.html?dl=0)

**Comment by selurvedu** [comment]
Дякую за репорт. :)

!cast @Leits

**Comment by selurvedu** [comment]
Ref: https://github.com/openprocurement/robot_tests.broker.privatmarket/pull/2#issuecomment-195485997

**Comment by selurvedu** [comment]
Ref: #99

**Comment by selurvedu** [comment]
Ref: #125

**Comment by selurvedu** [comment]
@AvchinnikovaOksana, має бути вирішено в #125.
